In [1]:
import duckdb
import pandas

In [2]:
sql_query = '''
show tables
'''

with duckdb.connect('data/chicago_crimes.db') as con:
    display(con.sql(sql_query).df())

                        name
0             chicago_crimes
1    gold_crimes_by_district
2  gold_crimes_by_month_type
3              silver_crimes
4         silver_crimes_type

In [3]:
with duckdb.connect('/workspace/data/chicago_crimes.db', read_only=True) as con:
    df = con.sql("select * from gold_crimes_by_month_type order by 1, 3 desc").df()

df.head()

       month         primary_type  total_crimes  total_arrests  arrest_rate
0 2026-01-01                THEFT          3701          385.0        0.104
1 2026-01-01              BATTERY          3027          651.0        0.215
2 2026-01-01      CRIMINAL DAMAGE          1820           80.0        0.044
3 2026-01-01              ASSAULT          1438          204.0        0.142
4 2026-01-01  MOTOR VEHICLE THEFT          1334           44.0        0.033

In [4]:
con = duckdb.connect('/workspace/data/chicago_crimes.db', read_only=True)
con.sql("show all tables").show()
con.sql("describe chicago_crimes").show()

┌────────────────┬─────────┬────────────────┬──────────────────────┬───────────────────────────────────────┬───────────┐
│    database    │ schema  │      name      │     column_names     │             column_types              │ temporary │
│    varchar     │ varchar │    varchar     │      varchar[]       │               varchar[]               │  boolean  │
├────────────────┼─────────┼────────────────┼──────────────────────┼───────────────────────────────────────┼───────────┤
│ chicago_crimes │ main    │ chicago_crimes │ [ID, Case Number, …  │ [BIGINT, VARCHAR, TIMESTAMP, VARCHA…  │ false     │
└────────────────┴─────────┴────────────────┴──────────────────────┴───────────────────────────────────────┴───────────┘

┌──────────────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│     column_name      │ column_type │  null   │   key   │ default │ extra │
│       varchar        │   varchar   │ varchar │ varchar │ varchar │ int32 │
├──────────────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ ID                   │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
│ Case Number          │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Date                 │ TIMESTAMP   │ YES     │ NULL    │ NULL    │  NULL │
│ Block                │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ IUCR                 │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Primary Type         │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Description          │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Location Description │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Arrest               │ BOOLEAN     │ YES     │ NULL    │ NULL    │  NULL │
│ Domestic             │ BOOLEAN     │ YES     │ NULL    │ NULL    │  NULL │
│ Beat                 │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ District             │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Ward                 │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
│ Community Area       │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
│ FBI Code             │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ X Coordinate         │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
│ Y Coordinate         │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
│ Year                 │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
│ Updated On           │ TIMESTAMP   │ YES     │ NULL    │ NULL    │  NULL │
│ Latitude             │ DOUBLE      │ YES     │ NULL    │ NULL    │  NULL │
│ Longitude            │ DOUBLE      │ YES     │ NULL    │ NULL    │  NULL │
│ Location             │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
├──────────────────────┴─────────────┴─────────┴─────────┴─────────┴───────┤
│ 22 rows                                                        6 columns │
└──────────────────────────────────────────────────────────────────────────┘

In [4]:
with duckdb.connect('/workspace/data/chicago_crimes.db', read_only=True) as con:
    df = con.sql("""
        select * from gold_crimes_by_month_type
        order by month, total_crimes desc
    """).df()

df.head(10)

       month         primary_type  total_crimes  total_arrests  arrest_rate
0 2026-01-01                THEFT          3701          385.0        0.104
1 2026-01-01              BATTERY          3027          651.0        0.215
2 2026-01-01      CRIMINAL DAMAGE          1820           80.0        0.044
3 2026-01-01              ASSAULT          1438          204.0        0.142
4 2026-01-01  MOTOR VEHICLE THEFT          1334           44.0        0.033
5 2026-01-01        OTHER OFFENSE          1253          219.0        0.175
6 2026-01-01   DECEPTIVE PRACTICE          1236           37.0        0.030
7 2026-01-01             BURGLARY           749           37.0        0.049
8 2026-01-01            NARCOTICS           577          553.0        0.958
9 2026-01-01    CRIMINAL TRESPASS           456          145.0        0.318